### ISSUE TITLE
fixCanvas doesn't appear to work?

### ISSUE THREAD

**Issue by iantait** [GaryStanton/ColdThumbs#1]
Hi,

Using 

`Local.testImage = Application.com.coldThumbs.getThumbnail(
													src						= Local.thisImage
												,	width					= 600
												,	height					= 600
												,	fixCanvas 				= true
												,	backgroundColor			= '000000'
												,	regenerate 				= true
													
);`

Never creates an image with a different canvas size.
Am I missing something?

Ta.

**Comment by GaryStanton** [comment]
Hi Ian,
Thanks for letting me know! I've fixed the issue and added a new test for it. 
Please note that the FixCanvas method only works with native resizing for the moment.
Can you give it a go and let me know if it's all working as expected now?

I also accidentally bumped the minor rather than the patch, but I guess since fixCanvas hasn't been working it might be considered new functionality? ;)

**Comment by iantait** [comment]
Hi,

It doesn't create the thumbs at all now, or produce an error that I can see.
Local.testImage.getStatus() reports 'Resizing' or 'Queued'.
I am on Lucee 4.5 though - I'll upgrade and see what happens.

**Comment by GaryStanton** [comment]
Ahh, yes... there is an issue I'm aware of with Lucee 4.5, paritally mitigated in earlier versions of the 5.x release and fully fixed in recent versions.
This relates to duplicating an image object that doesn't actually contain image data. The fixed canvas functionality creates an empty image of the desired size and then pastes the resized image onto it - but Lucee chokes at the duplication.
You're probably not seeing an error because you're running it inside a thread. If you disable threading, you'll likely see the error 'Missing Format'.
There's a bug report here with a bit more detail: https://luceeserver.atlassian.net/browse/LDEV-1906

**Comment by iantait** [comment]
Just tried CF11 - works dandy - thanks,

**Comment by GaryStanton** [comment]
Great... I also found native resizing in ACF is much faster than in Lucee... The only time I've found that!
I'll close the issue off now then. Thanks for being my first user! Hope you find it useful. ;)

**Comment by iantait** [comment]
I'd be interested in this working with imagemagick BTW, probably less of a hit, and I'd imagine, quicker.

**Comment by GaryStanton** [comment]
Sure... it's on the list. ImageMagick support was a last minute addition after I found the native resizing to perform so poorly in a project I was running on Lucee. I'll update this issue when fixedCanvas is running in IM.

**Comment by iantait** [comment]
I've just munged it locally to test - seems adding

-gravity center -extent #Arguments.width GT 0 ? Arguments.width : ''##Arguments.height GT 0 ? 'x' & Arguments.height : ''#

to the cfexecute call does look like its doing what I want.



________________________________

**Comment by GaryStanton** [comment]
Cool! That looks like it'll work, however looking at the docs it says it'll crop over resize if the image is is bigger than the new canvas. I've not tested it out yet.
Will also need to add background colour.
Fee free to add a PR if you can address these issues, otherwise I'll take a look at it this evening.

**Comment by GaryStanton** [comment]
I've got the fixCanvas functionality working in ImageMagick the same way as native.
i.e. the canvas will remain the size set, while the image is proportionally resized to fit inside it without cropping.
Check out v2.1.1 and let me know how you get on!
